### ISSUE TITLE
Move all docker files to tf images repo

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tf_jukebox#27] opened 2021-06-08 13:17 UTC
Currently blockchain solutions in https://github.com/threefoldtech/vdc-solutions-charts repo is used with kubernetes

to be able to use it as flist we need to know the entrypoint and env variables or examples to run it on docker

**Comment by ashraffouda** [comment] 2021-06-24 11:22
duplicate of https://github.com/threefoldtech/tf-images/issues/32

**Closed by ashraffouda** 2021-06-24 11:22 UTC
Labels: priority_major, type_feature
