### ISSUE TITLE
add casperlabs

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/tf_jukebox#37] opened 2021-06-13 12:48 UTC
### deliverables:
 - flist for substrate on [tf-images](https://github.com/threefoldtech/tf-images)
 - docs
 
 
 part of https://github.com/threefoldtech/home/issues/1082

**Comment by ashraffouda** [comment] 2021-06-24 09:41
duplicate of https://github.com/threefoldtech/tf-images/issues/35

**Closed** 2021-06-24 09:41 UTC
